#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="$(mktemp -d "${TMPDIR:-/tmp}/herdr-install-test.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/bin" "$TMP/home"
LOG="$TMP/herdr.log"
STATE="$TMP/herdr.state"

cat > "$TMP/bin/herdr" <<'FAKE'
#!/usr/bin/env bash
set -euo pipefail
case "${1:-}" in
  --skill)
    printf '%s\n' '---' 'name: herdr' '---' '# Generated by the installed Herdr binary.'
    ;;
  plugin)
    case "${2:-}" in
      list)
        if [ -f "$HERDR_TEST_STATE.plugins" ]; then
          printf '%s\n' \
            '- file-viewer [github:smarzban/herdr-file-viewer@fa1946a04dd58ba9b3db2eda0125b6055fb604da]' \
            '- reviewr [github:persiyanov/herdr-reviewr@42ccaaa72176937181c82a91484f97466fb5ed59]'
        fi
        [ ! -f "$HERDR_TEST_STATE.local" ] \
          || printf '%s\n' "- local [local:$HERDR_TEST_LOCAL]"
        ;;
      install) printf '%s\n' "$*" >> "$HERDR_TEST_LOG"; : > "$HERDR_TEST_STATE.plugins" ;;
      link) printf '%s\n' "$*" >> "$HERDR_TEST_LOG"; : > "$HERDR_TEST_STATE.local" ;;
      *) exit 2 ;;
    esac
    ;;
  integration)
    case "${2:-}" in
      status)
        [ ! -f "$HERDR_TEST_STATE.integrations" ] \
          || printf '%s\n' 'claude: current (v1) (/example)' 'codex: current (v1) (/example)'
        ;;
      install) printf '%s\n' "$*" >> "$HERDR_TEST_LOG"; : > "$HERDR_TEST_STATE.integrations" ;;
      *) exit 2 ;;
    esac
    ;;
  *) exit 2 ;;
esac
FAKE
chmod +x "$TMP/bin/herdr"

export PATH="$TMP/bin:$PATH"
export HOME="$TMP/home"
export HERDR_CONFIG_FILE="$TMP/home/config/herdr/config.toml"
export HERDR_SKILL_FILE="$TMP/home/skills/herdr/SKILL.md"
export HERDR_TEST_LOG="$LOG"
export HERDR_TEST_STATE="$STATE"
export HERDR_TEST_LOCAL="$TMP/local-plugin"
mkdir "$HERDR_TEST_LOCAL"

fail() { printf 'FAIL: %s\n' "$*" >&2; exit 1; }

if "$ROOT/bin/install-herdr" >/dev/null 2>&1; then
  fail "installation did not require explicit adoption"
fi
[ ! -e "$HERDR_CONFIG_FILE" ] || fail "implicit invocation wrote config"

mkdir -p "$(dirname "$HERDR_CONFIG_FILE")"
printf 'unmanaged\n' > "$HERDR_CONFIG_FILE"
"$ROOT/bin/install-herdr" --adopt >/dev/null
[ -s "$HERDR_CONFIG_FILE" ] || fail "adoption did not render config"
[ -s "$HERDR_SKILL_FILE" ] || fail "adoption did not generate upstream skill"
rg -q "$ROOT/bin/herdr-confirm-close-pane" "$HERDR_CONFIG_FILE" \
  || fail "helper directory token was not rendered"
! rg -q '@HELPER_DIR@' "$HERDR_CONFIG_FILE" \
  || fail "rendered config retained its token"
shopt -s nullglob
backups=("$HERDR_CONFIG_FILE".backup.*)
shopt -u nullglob
[ "${#backups[@]}" -eq 1 ] || fail "adoption did not back up unmanaged config"

"$ROOT/bin/install-herdr" --check >/dev/null \
  || fail "check rejected a current installation"
printf '\n# drift\n' >> "$HERDR_CONFIG_FILE"
if "$ROOT/bin/install-herdr" --check >/dev/null 2>&1; then
  fail "check accepted drifted config"
fi
"$ROOT/bin/install-herdr" --adopt --plugins --integrations claude,codex \
  --local-confirmation-plugin "$HERDR_TEST_LOCAL" >/dev/null
"$ROOT/bin/install-herdr" --check --plugins --integrations claude,codex \
  --local-confirmation-plugin "$HERDR_TEST_LOCAL" >/dev/null \
  || fail "scoped check rejected installed plugins or integrations"

[ "$(rg -c '^plugin install ' "$LOG")" -eq 2 ] \
  || fail "immutable public plugins were not installed"
rg -q '^integration install claude$' "$LOG" \
  || fail "Claude integration was not explicit"
rg -q '^integration install codex$' "$LOG" \
  || fail "Codex integration was not explicit"

printf 'herdr install regression: ok\n'
